cpu = "1"
ram = "1024"

Vagrant.configure("2") do |config|

  # Box to create VM from
  config.vm.box = "Ubuntu-1604-virtualbox"
  
  # Box version to use (latest)
  config.vm.box_version = ">= 0"

  # Check box update during vagrant up
  config.vm.box_check_update = true

  # Check checksum after box download
  config.vm.box_download_checksum = true

  # Set checksum type
  config.vm.box_download_checksum_type = "sha1"

  # Check SSL certificate before box download
  config.vm.box_download_insecure = false

  # SSH for linux and winrm for Windows
  config.vm.communicator = "ssh"
  
  # Replace default insecure SSH key
  config.ssh.insert_key = false

  # SSH username
  config.ssh.username = "vagrant"

  # Shell to use via SSH
  config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"

  # Setup first server
  config.vm.define "svr1" do |svr1|

    # Set VM hostname
    svr1.vm.hostname = "svr1"

    # Set port forwarding 
    svr1.vm.network "forwarded_port", guest: "80", host: "8080", host_ip: "127.0.0.1", protocol: "tcp", auto_correct: true

    # Set VM CPU & RAM limits
    svr1.vm.provider "virtualbox" do |v|
        v.customize ["modifyvm", :id, "--cpuexecutioncap", "75"]
        v.memory = "512"
        v.cpus = "1"
    end    

    # Execute external script
    svr1.vm.provision "shell", path: "update.sh"
        
    # Execute Ansible playbook
    svr1.vm.provision "ansible" do |ansible|
      ansible.playbook = "apache.yml"
      ansible.sudo = true
    end

    # Seconds to wait during gracefull halt
    svr1.vm.graceful_halt_timeout = "120"

  end

  # Setup second server
  config.vm.define "svr2" do |svr2|

    # Set VM hostname
    svr2.vm.hostname = "svr2"

    # Set port forwarding 
    svr2.vm.network "forwarded_port", guest: "80", host: "8090", host_ip: "127.0.0.1", protocol: "tcp", auto_correct: true

    # Set VM CPU & RAM limits
    svr2.vm.provider "virtualbox" do |v|
        v.customize ["modifyvm", :id, "--cpuexecutioncap", "75"]
        v.memory = "512"
        v.cpus = "1"
    end    

    # Execute external script
    svr2.vm.provision "shell", path: "update.sh"
        
    # Execute Ansible playbook
    svr2.vm.provision "ansible" do |ansible|
      ansible.playbook = "nginx.yml"
      ansible.sudo = true
    end

    # Seconds to wait during gracefull halt
    svr2.vm.graceful_halt_timeout = "120"

  end

end
